### ISSUE TITLE
Not reading labels from xml files

### ISSUE THREAD

**Issue by ammarmahmood** [experiencor/keras-yolo3#101]
Hi,

I am getting the following error when I call the train function:

`python train.py -c config.json
Using TensorFlow backend.
Seen labels:    {'lobster': 460}

Given labels:   ['lobster', 'n01984695']
Some labels have no annotations! Please revise the list of labels in the config.json.
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 182, in _main_
    config['model']['labels']
ValueError: not enough values to unpack (expected 4, got 3)`

The code runs fine when I only have the lobster class in the annotations. 

What might be causing this?

**Comment by darjoo** [comment]
The problem is that within your config.json, you supply the following labels `['lobster', 'n01984695']`. However, you only have `['lobster']` labels within your dataset. Just remove the second label in your config.json and it'll be fine.

**Comment by ammarmahmood** [comment]
I have xml files from three different sources but all in the voc format. The training module is only able to read labels from one type of the files.

**Comment by ammarmahmood** [comment]
[type1.txt](https://github.com/experiencor/keras-yolo3/files/2096633/type1.txt)
[type2.txt](https://github.com/experiencor/keras-yolo3/files/2096634/type2.txt)
[type3.txt](https://github.com/experiencor/keras-yolo3/files/2096635/type3.txt)


Labels from  only type 3 files are being loaded. (I have cinverted the files to .txt because can,t attach xml files here. )

**Comment by darjoo** [comment]
That is very strange. All 3 label files look right and in the correct format to me. If no.1 isn't your issue, take a look at 2.

1. Possible issue you're facing is caching error. Because you had run it before (only with `'lobsters'`, it created a cache and now only loads it even though you changed your dataset) Remove it or comment the cache portion of the code out.
2. Go into debug mode and take a look at `voc.py` at line 45. Technically if should never reach there unless you didn't add the label in `config.json`. If it never touches it, go further up to make sure that it is actually reading in your other label.

I can't think of other possibilities at the moment but keep me informed and I'll try and help as best I can.

**Comment by ammarmahmood** [comment]
No. 1 worked. The cache was the issue. Thanks a lot for the quick help!

**Comment by PoonamZ** [comment]
Hi,
I am facing the problem as,
python3 train.py -c config.json
Using TensorFlow backend.
Seen labels: 	{'working_chimney': 146, 'unworking_condensing_tower': 329, 'working_condensing_tower': 277, 'unworking_chimney': 347}

Given labels: 	['powerplant']
Some labels have no annotations! Please revise the list of labels in the config.json.
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 182, in _main_
    config['model']['labels']
ValueError: not enough values to unpack (expected 4, got 3)


Please can you suggest the solution.

**Comment by jithin454** [comment]
AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'


this is the error when i am running it.
please help me to solve this

**Comment by ajupar** [comment]
"Possible issue you're facing is caching error. Because you had run it before (only with 'lobsters', it created a cache and now only loads it even though you changed your dataset) Remove it or comment the cache portion of the code out."

Thanks, I had the same issue and removing the cache file (.pkl) solved it.
